esphome:
  name: nodemcu-01
  friendly_name: IOT ESP ANS
  platformio_options: {}
  includes: []
  libraries: []

esp8266:
  board: nodemcuv2
  framework:
    version: recommended

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "LnbRli25aVNDpnp6K0g30AXgm9SZTng03tsCcuhQeUY="

ota:
  password: "28f5a1c62a427566dd07ae2dcb9e2a34"

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IOT ESP ANS"
    password: !secret wifi_password

  power_save_mode: NONE
  output_power: 20.0
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_password'

sensor:
  - platform: absolute_humidity
    id: hum_abs_1
    name: wilgotnosc_bezwzgledna_1
    temperature: temp_1
    humidity: hum_1
    disabled_by_default: false
    force_update: false
    unit_of_measurement: g/m³
    accuracy_decimals: 1
    equation: WOBUS

  - platform: dht
    pin:
      number: 5
      mode:
        input: true
        analog: false
        output: false
        open_drain: false
        pullup: true
        pulldown: false
      inverted: false
    model: DHT11
    temperature:
      id: temp_1
      name: temperatura_1
      disabled_by_default: false
      force_update: false
      unit_of_measurement: °C
      accuracy_decimals: 0
    humidity:
      id: hum_1
      name: wilgotnosc_1
      disabled_by_default: false
      force_update: false
      unit_of_measurement: '%'
      accuracy_decimals: 0
    update_interval: 30s 

  - platform: wifi_signal
    id: wifi_signal_db
    name: wifi_signal_1
    update_interval: 30s
    unit_of_measurement: "dB"

switch:
  - platform: gpio
    pin:
      number: 14
      mode:
        output: true
        analog: false
        input: false
        open_drain: false
        pullup: false
        pulldown: false
      inverted: false
    name: relay_1
    id: relay_01
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    interlock_wait_time: 0ms
    
  - platform: gpio
    pin:
      number: 12
      mode:
        output: true
        analog: false
        input: false
        open_drain: false
        pullup: false
        pulldown: false
      inverted: false
    name: relay_2
    id: relay_02
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    interlock_wait_time: 0ms

  - platform: gpio
    pin:
      number: 2
      mode:
        output: true
        analog: false
        input: false
        open_drain: false
        pullup: false
        pulldown: false
      inverted: false
    id: led_01
    name: led_onboard_1
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: false
    interlock_wait_time: 0ms

  - platform: gpio
    pin: 
      number: 16
      mode:
        output: true
        analog: false
        input: false
        open_drain: false
        pullup: false
        pulldown: false
      inverted: false
    id: led_02
    name: led_onboard_2
    inverted: true
    restore_mode: RESTORE_DEFAULT_ON
    disabled_by_default: false
    interlock_wait_time: 0ms

captive_portal: {}
  
web_server:
  port: 80
  id: web_serv_1
  include_internal: true
  version: 2
  ota: true
  auth:
    username: rafal
    password: jedryka